server:
  #配置访问的端口
  port: 8001
  #配置访问时的项目名 
  servlet:
    context-path: /dsdemo
spring:
  profiles:
    include: db
mybatis:
  typeAliasesPackage: com.qizy.dynimaticds.entity
  mapperLocations: classpath:mapper/*.xml